title: "Nikolas Xiros"
description: "Short bio line..."
theme: jekyll-theme-minimal  # or 'cayman', 'slate', 'architect'

# Navigation bar (for themes that support it)
# Cayman will use these as buttons at the top
navigation:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects/
  - title: "About"
    url: /about/
  - title: "Personal Interests"
    url: /interests/