title: "Nikolas Xi̱ros"
description: "Nikolas Xiros — AI researcher at ISLP, Athena Research Center, working on NLP, multimodal learning, interpretability and AI safety."
theme: jekyll-theme-cayman  
url: "https://nickxir12.github.io"
baseurl: ""

include:
  - assets/css